module.exports = {
  apps: [
    {
      name: 'netma-server',
      cwd: './server',
      script: 'node',
      args: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '.env',
      error_file: '../logs/netma-error.log',
      out_file: '../logs/netma-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      watch: false,
      merge_logs: true,
    },
    {
      name: 'netma-client',
      cwd: './client',
      script: './node_modules/.bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      env: { PORT: '3000', NODE_ENV: 'production' },
      error_file: '../logs/client-error.log',
      out_file: '../logs/client-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      watch: false,
      merge_logs: true,
    },
  ],
};
