module.exports = {
  apps: [
    {
      name: 'netma-server',
      cwd: './server',
      script: 'node',
      args: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env_file: '../.env',
      error_file: '../logs/netma-error.log',
      out_file: '../logs/netma-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      watch: false,
      merge_logs: true,
    },
    {
      name: 'netma-client',
      cwd: './server',
      script: 'node',
      args: 'serve-frontend.js',
      instances: 1,
      exec_mode: 'fork',
      env: { FE_PORT: '3000' },
      error_file: '../logs/client-error.log',
      out_file: '../logs/client-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 5000,
      watch: false,
      merge_logs: true,
    },
  ],
};
